name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:unstable
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          apt update
          apt install -y libgtk-3-dev valac meson
      - name: Build
        run: |
          meson build
          ninja -C build
          ninja -C build install
